Niikita layer
very-important-unmutable-organization/equipment pull request #15
Opened 2022-01-16 17:47 UTC by asdminerpro

@StephanYorchenko жду ревью

2022-01-16 18:54 UTC, StephanYorchenko commented on src/cmd/main.go
> +//
ну я тоже могу 1k строк комментариями набить

2022-01-16 19:00 UTC, asdminerpro commented on src/cmd/main.go
> +//
это я закомментил, чтобы работало
не всё еще на слои разнелось просто.

2022-01-16 19:01 UTC, StephanYorchenko requested changes
вроде норм, но многовато закомментированного кода и предгенеренных свагер-файлов, словно автор хотел накрутить контрибьюты в проекте

2022-01-18 08:06 UTC, EinKrebs commented on src/internal/repository/equipment.go
> +	equipment domain.Equipment //nolint:structcheck,unused
@asdminerpro зачем это здесь?

2022-01-18 08:11 UTC, asdminerpro commented on src/internal/repository/equipment.go
> +	equipment domain.Equipment //nolint:structcheck,unused
типо зависимость репозитория от модельки которая бд описывает......
которую я видимо нигде не заюзал

2022-01-25 17:56 UTC, merged